import type { ArchiveDetail } from "@/content/types";
import { archiveProjects } from "@/content/archive";

// Long-form archive project pages, ported from their original Squarespace
// source as directly as possible. Two deliberate departures from source,
// per an explicit request: awards/press ("recognition") moved up near the
// tags instead of sitting at the page bottom, and the source page's "other
// projects" links at the very bottom are dropped entirely.
export const archiveDetails: Record<string, ArchiveDetail> = {
  "she-served": {
    slug: "she-served",
    recognition: [
      {
        label: "Core77 Student Runner Up",
        href: "http://designawards.core77.com/2017/Strategy-Research",
        detail: "Strategy & Research / 2017",
        icon: "award",
      },
      {
        label: "Core77 Student Notable",
        href: "http://designawards.core77.com/2017/Design-for-Social-Impact",
        detail: "Design for Social Impact / 2017",
        icon: "award",
      },
      {
        label: "The Race",
        href: "https://www.denver7.com/news/national/female-veterans-face-separate-struggles-than-their-male-counterparts",
        detail: "Denver 7 News",
        icon: "newspaper",
      },
      {
        label: "Vantage Point",
        href: "https://web.archive.org/web/20250415125051/https://news.va.gov/38724/va-partners-with-new-yorks-school-of-visual-arts-to-promote-cultural-transformation/",
        detail: "Official Blog of the U.S. Department of Veterans Affairs",
        icon: "newspaper",
      },
    ],
    blocks: [
      {
        type: "paragraph",
        text: "The She Served Project is a campaign and storytelling initiative aimed at increasing visibility and understanding of women veterans in the United States.",
      },
      {
        type: "paragraph",
        text: "It was researched and developed in partnership with the NY Veterans Affairs office under the guidance of IDEO’s Lawrence Abrahamson as part of the Design Research and Integration class at Products of Design in 2017. I worked alongside classmates Alexia Cohen, Kevin Cook, Jiani Lin, Antriksh Nangia, and Teng Yu.",
      },
      {
        type: "image",
        src: "/images/she-served/01-billboard.webp",
        width: 2500,
        height: 1667,
        alt: "A speculative ad from our proposed participatory campaign.",
        caption: "A speculative ad from our proposed participatory campaign.",
      },
      { type: "heading", level: 2, text: "Women veterans are veterans too." },
      {
        type: "paragraph",
        text: "We spent fifteen weeks researching public perceptions of women veterans — and designing to change them. Here’s what we learned:",
      },
      {
        type: "image",
        src: "/images/she-served/02-tangible-insights.webp",
        width: 1920,
        height: 1080,
        alt: "We developed ‘tangible insights’ to visualize and validate our learnings.",
        caption: "We developed ‘tangible insights’ to visualize and validate our learnings.",
      },
      {
        type: "paragraph",
        text: "Women veterans are far less likely to outwardly project their veteran identity than their male counterparts.",
      },
      {
        type: "image",
        src: "/images/she-served/03-tangible-insight-victim.webp",
        width: 1920,
        height: 1080,
        alt: "A tangible insight artifact representing how women veterans are perceived.",
      },
      {
        type: "paragraph",
        text: "Women vets feel that the media is more likely to portray them as victims than as heroes.",
      },
      {
        type: "image",
        src: "/images/she-served/04-game-of-military-life.webp",
        width: 1920,
        height: 1080,
        alt: "I wrote and designed The Game of Military Life to showcase the stark differences of the women veteran’s experience.",
        caption: "I wrote and designed The Game of Military Life to showcase the stark differences of the women veteran’s experience.",
      },
      {
        type: "paragraph",
        text: "Both during and after active duty, military women tend to feel like the deck is stacked against them. We made a board game to show all the obstacles and excuses that make succeeding in the military — and just maintaining physical and mental health — such a challenge for women.",
      },
      {
        type: "image",
        src: "/images/she-served/05-game-cards.webp",
        width: 1920,
        height: 1080,
        alt: "Men are more likely to get good chances for advancement, while women constantly encounter excuses that keep them from the best opportunities.",
        caption: "Men are more likely to get good chances for advancement, while women constantly encounter excuses that keep them from the best opportunities.",
      },
      {
        type: "image",
        src: "/images/she-served/06-military-game-players.webp",
        width: 1920,
        height: 1080,
        alt: "Women currently make up 15% of active duty troops — with that number on the rise.",
        caption: "Women currently make up 15% of active duty troops — with that number on the rise.",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "Prompted by the question “How might we establish a new cultural norm that a woman veteran is also a veteran?”, we read everything we could about the woman veteran’s experience — and then we started interviewing. In two weeks, we conducted 10 expert interviews with women veterans and VA staff, 27 intercept interviews of civilians, and topped things off with an online survey.",
      },
      {
        type: "image",
        src: "/images/she-served/07-process-image.webp",
        width: 1920,
        height: 1080,
        alt: "Research synthesis from the interview and survey process.",
      },
      {
        type: "paragraph",
        text: "We distilled a sea of quotes into insights and verified them with stakeholders using the tangible insights seen above. We refined our thinking into a final array of design principles — in the form of more pointed “how might we” questions — that we used to kick-start the ideation process.",
      },
      { type: "heading", level: 2, text: "Proposal" },
      {
        type: "imagePair",
        images: [
          {
            src: "/images/she-served/08-proposal-fullsize-1.webp",
            width: 1920,
            height: 1080,
            alt: "Proposal concept artwork, full size.",
          },
          {
            src: "/images/she-served/09-proposal-fullsize-2.webp",
            width: 1920,
            height: 1080,
            alt: "Proposal concept artwork, full size.",
          },
        ],
      },
      {
        type: "paragraph",
        text: "The #SheServed initiative is aimed at building public perception of women as an equal and significant part of the veteran community in the United States. By combining a platform for celebrating women servicemembers’ achievements with an accessible, shareable brand identity, this experiential campaign can empower women veterans and deliver their stories to a larger audience.",
      },
      {
        type: "image",
        src: "/images/she-served/10-general-public-screenshot.webp",
        width: 2500,
        height: 1406,
        alt: "The general public is introduced (in their own voice) to the misperceptions and biases women vets encounter every day.",
        caption: "The general public is introduced (in their own voice) to the misperceptions and biases women vets encounter every day.",
      },
      {
        type: "image",
        src: "/images/she-served/11-brand-identity.webp",
        width: 2500,
        height: 1406,
        alt: "The #SheServed brand identity system.",
      },
      { type: "heading", level: 3, text: "Wearable campaign" },
      {
        type: "paragraph",
        text: "Inspired by the Livestrong campaign’s success in creating momentum around cancer research in the mid-2000s, the #SheServed campaign uses stark iconography and an eye-catching palette to increase recognition of the issues female veterans face. To wear the #SheServed insignia is to support the following statement:",
      },
      {
        type: "quote",
        text: "The service and sacrifices of women veterans are equally significant to those of their male counterparts. I stand with veterans — women vets included — in their search for recognition and fair treatment.",
      },
      {
        type: "paragraph",
        text: "Targeted to resonate with veterans, their families and the public at large, the campaign’s messaging encourages viewers to show support by wearing pins, hats and other #SheServed-branded collateral.",
      },
      {
        type: "image",
        src: "/images/she-served/12-storyboard-male-veterans.webp",
        width: 1920,
        height: 1080,
        alt: "Support for the campaign from male veterans is crucial to its normalization in the military.",
        caption: "Support for the campaign from male veterans is crucial to its normalization in the military.",
      },
      {
        type: "paragraph",
        text: "By driving participants to share hashtagged images of their #SheServed gear on social media, the campaign may grow its footprint at an exponential rate. And the more #SheServed gear gets bought, the more proceeds go to non-profits actively combatting serious issues for veterans, such as homelessness and inadequate mental health care.",
      },
      { type: "label", text: "Wearable campaign: how it works" },
      {
        type: "paragraph",
        text: "Limited advertising spend upfront could kick-start a self-reinforcing loop of earned media through participants’ social channels. The more swag they buy, the more acceptance of women veterans is normalized — and the more money goes to helping those most in need.",
      },
      {
        type: "image",
        src: "/images/she-served/13-wearable-how-it-works.webp",
        width: 2500,
        height: 1406,
        alt: "Diagram showing how the wearable campaign's earned-media loop works.",
      },
      { type: "heading", level: 3, text: "Postcard Stories" },
      {
        type: "paragraph",
        text: "The Postcard Stories Project provides a platform where women servicemembers’ stories and achievements can be shared and celebrated, leveraging the military’s team-first mentality to get vets to celebrate their peers. Vets receive blank postcards that invite them to share a story about an outstanding woman peer. Stories are submitted to the SheServed team, where selections are posted to the campaign’s blog and social channels.",
      },
      {
        type: "image",
        src: "/images/she-served/14-postcard-distribution.webp",
        width: 1920,
        height: 1080,
        alt: "Some vets are reached by mail, while others pick up blank cards at their local VA or VSO clubhouse.",
        caption: "Some vets are reached by mail, while others pick up blank cards at their local VA or VSO clubhouse.",
      },
      {
        type: "image",
        src: "/images/she-served/15-postcard-writing.webp",
        width: 1920,
        height: 1080,
        alt: "Vets hand-write their stories on the blank back and mail in pre-paid postcards for curation and aggregation.",
        caption: "Vets hand-write their stories on the blank back and mail in pre-paid postcards for curation and aggregation.",
      },
      {
        type: "image",
        src: "/images/she-served/16-postcard-social.webp",
        width: 1920,
        height: 1080,
        alt: "Select stories appear on the campaign blog and are distributed on social channels — reaching veterans and reinforcing women vets’ sense of value.",
        caption: "Select stories appear on the campaign blog and are distributed on social channels — reaching veterans and reinforcing women vets’ sense of value.",
      },
      {
        type: "image",
        src: "/images/she-served/17-postcard-blank.webp",
        width: 1920,
        height: 1080,
        alt: "The blank post-card, featuring a blank back (for story-writing) and a tear-off bookmark.",
        caption: "The blank post-card, featuring a blank back (for story-writing) and a tear-off bookmark.",
      },
      { type: "label", text: "Postcard stories: how it works" },
      {
        type: "paragraph",
        text: "Blank cards are sent to veterans through several channels before stories are sent back to SheServed with prepaid postage. Stories are curated and distributed through the blog, owned social, gallery shows and a printed book — getting the positive messaging in front of both veterans and civilians.",
      },
      {
        type: "paragraph",
        text: "As the stories reach a critical mass, the campaign can extend into the physical domain — through gallery shows and a printed book — to reach and inspire civilians outside of the military bubble.",
      },
      {
        type: "image",
        src: "/images/she-served/18-postcard-how-it-works.webp",
        width: 2500,
        height: 1406,
        alt: "Diagram showing how the postcard stories distribution loop works.",
      },
    ],
    sourceLink: {
      label: "this story on the Products of Design blog",
      href: "http://productsofdesign.sva.edu/blog/designing-for-women-vets-cultural-norms",
    },
  },
  thesis: {
    slug: "thesis",
    recognition: [],
    blocks: [
      {
        type: "paragraph",
        text: "The work and writing below was developed in 2017–2018 for my master’s thesis at [Products of Design, SVA](https://productsofdesign.sva.edu/).",
      },
      {
        type: "paragraph",
        text: "As artificial intelligence’s capabilities continue to expand, there’s a growing anxiety that the impending AI Revolution may automate more jobs than it creates — triggering a crisis of worker displacement to rival the Dust Bowl and the Great Depression. In response, I developed *Me, Myself and A.I.: How I Learned to Love the Machine That Took my Job*, a thesis of speculative designs that imagine near and distant futures where AI is used to increase individual agency — not diminish it.",
      },
      {
        type: "paragraph",
        text: "Developed in my second and final year at SVA’s Products of Design MFA program, these proposals and provocations address access to work and other ways to protect human dignity in an automated age. Because while the Hollywood definition of AI may still be light-years away, AI is already taking over the world.",
      },
      {
        type: "video",
        provider: "vimeo",
        id: "278203025",
        caption: "Watch me present thesis highlights at the SVA Theater (2018)",
      },
      {
        type: "paragraph",
        text: "The full fruits of a year’s worth of research, sketching, ideation, prototyping, and design are showcased in my thesis book, available for [download here](https://willcrum.itch.io/mmai) — all 194 pages of it. Below are snapshots of a few key projects, plus links to more detailed pages for each project’s origin, development process, and final form.",
      },
      {
        type: "pdf",
        url: "https://pub-1e1e0e4d047847bbad37d4cf58fd6bab.r2.dev/thesis.pdf",
        previewUrl: "https://pub-1e1e0e4d047847bbad37d4cf58fd6bab.r2.dev/thesis-preview.pdf",
        caption: "Click through the full thesis book above.",
      },
    ],
    // Derived rather than duplicated — these are the same entries that
    // appear as their own cards on the /archive index page (see
    // content/archive.ts), so both stay in sync automatically.
    subProjects: archiveProjects.filter(
      (p) => p.category === "Thesis" && p.slug !== "thesis",
    ),
    closingBlocks: [
      {
        type: "paragraph",
        text: "While my thesis may be complete, the issues it addressed and the egalitarian agenda I established are still close to my heart. If you were intrigued by my work, I’d love to chat! Contact me at [willacrum@gmail.com](mailto:willacrum@gmail.com).",
      },
    ],
  },
  babi: {
    slug: "babi",
    recognition: [],
    blocks: [
      {
        type: "paragraph",
        text: "Babi is a speculative connected device meant to hold a mirror to how we value our personal data. We already let Amazon and Google mine our daily lives for profit through Alexa and Google Home. How might things be different when an artificial general intelligence is running the show?",
      },
      {
        type: "image",
        src: "/images/babi/02-billboard.webp",
        width: 2000,
        height: 1125,
        alt: "A billboard in the not-so-distant future",
        caption: "A billboard in the not-so-distant future.",
      },
      { type: "paragraph", text: "The year is 2118." },
      {
        type: "paragraph",
        text: "A few decades ago, an artificial superintelligence named “GovIntel” wrested power from the human elite and assumed the role of benevolent dictator. Now, GovIntel doles out social services, allots food and shelter, assigns roles and responsibilities, and generally keeps the trains running. Every household gets a fair allotment in exchange for chipping in with their neighborhood chores.",
      },
      {
        type: "paragraph",
        text: "But some people still doubt GovIntel’s ability to fully understand the human experience. To allay these concerns, GovIntel developed babi. Babi is an anthropomorphic robot that lives in a family’s home, observes their daily interactions, and builds a more detailed model of their unique wants and needs. Babi reports these insights back to GovIntel, enabling it to better tailor the services it provides to the host family.",
      },
      {
        type: "paragraph",
        text: "Adopting a babi is far from mandatory, but families that express discomfort with GovIntel’s role are encouraged to give it a try. And to encourage their full interaction with babi, the robot simulates all of the emotional and learning processes of a human newborn — besides eating. If properly incorporated into the family’s space and dialogue, babi will learn to speak in full sentences within a year.",
      },
      {
        type: "paragraph",
        text: "After that, the families are free to send their babi back, its model completed. But if they’ve grown attached...they’re welcome to keep it.",
      },
      {
        type: "image",
        src: "/images/babi/03-babi-product.webp",
        width: 2000,
        height: 1334,
        alt: "A babi unit, photographed as a physical product",
      },
      { type: "heading", level: 2, text: "Critical design" },
      {
        type: "paragraph",
        text: "Most people wouldn’t let a company put their picture on a billboard in Times Square without expecting some form of compensation. So why are we so indifferent to the fact that companies are building empires off the backs of our personal data?",
      },
      {
        type: "image",
        src: "/images/babi/04-data-flow-diagram.webp",
        width: 2000,
        height: 1125,
        alt: "Tech companies give us the tools that power our daily lives, but the data only flows one way",
        caption: "Tech companies give us the tools that power our daily lives, but the data only flows one way.",
      },
      {
        type: "paragraph",
        text: "Companies like Google, Facebook and Amazon offer us services like email, social networking and voice assistants for little or no financial cost. In exchange, but each of these services has a secondary purpose, invisible to the user but of chief importance to the company: data collection.",
      },
      {
        type: "paragraph",
        text: "Today’s tech heavyweights have repositioned themselves as AI companies, and customer data is the fuel that makes them go. But while most people are vaguely aware that their messages, searches, and purchases are all logged and recorded, what these companies do with that data remains a black box.",
      },
      {
        type: "paragraph",
        text: "But wouldn’t it be great if we got some sense of feedback on how our data ingestion process is going? Let alone some share of the spoils...",
      },
      {
        type: "image",
        src: "/images/babi/05-govintel-map.webp",
        width: 1920,
        height: 1080,
        alt: "Even when our primary interfaces for tech become AR contact lenses and audio, wouldn’t it be nice if our AI gave us a peek into its learning process?",
        caption: "Even when our primary interfaces for tech become AR contact lenses and audio, wouldn’t it be nice if our AI gave us a peek into its learning process?",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "Babi was conceived as a speculative object in the very early phases of my thesis exploration, and was borne of an interrogation of existing relationships with AI.",
      },
      {
        type: "imageGrid",
        columns: 3,
        images: [
          { src: "/images/babi/06-ai-baby-sketch.webp", width: 1411, height: 1411, alt: "An early exploratory sketch of Babi's anthropomorphic form" },
          { src: "/images/babi/07-process-01.webp", width: 1080, height: 1080, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/08-process-02.webp", width: 2000, height: 2000, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/09-process-03.webp", width: 1080, height: 1077, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/10-process-04.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/11-process-05.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/12-process-06.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/13-process-07.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/14-process-08.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/15-process-09.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/16-process-10.webp", width: 2000, height: 1500, alt: "Prototyping Babi's physical form and interactions" },
          { src: "/images/babi/17-process-11.webp", width: 1333, height: 2000, alt: "Prototyping Babi's physical form and interactions" },
        ],
      },
      {
        type: "image",
        src: "/images/babi/18-process-12.webp",
        width: 1333,
        height: 2000,
        alt: "A mock-up of a Babi print advertisement",
      },
    ],
  },
  "human-resourcing-dept": {
    slug: "human-resourcing-dept",
    recognition: [],
    blocks: [
      { type: "heading", level: 2, text: "The job placement agency of the future." },
      {
        type: "paragraph",
        text: "The Human Resourcing Dept. was a single-day interactive performance designed to provoke participants to imagine their new role in a future where their “old” job has been automated out of existence. Participants answered personal questions — asked by an “AI” named PETAR — and are sorted into a future job based on whether they prioritize their critical thinking, creative thinking, or emotional intuition. Developed as part of my master’s thesis, *Me, Myself & A.I.: How I Learned to Love the Machine That Took my Job*, this creative experiment was intended to test how people would react to having their career choice dictated to them by a machine.",
      },
      {
        type: "video",
        provider: "vimeo",
        id: "262981976",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/02-establishing.webp",
        width: 2000,
        height: 1313,
        alt: "The Human Resourcing Dept.'s waiting room, set dressed for 2088",
      },
      {
        type: "paragraph",
        text: "Participants were greeted by a receptionist, Ellen, who cordially asked that they scan their implant ID chip. “Oh, you don’t have an ID chip,” Ellen realized aloud. “May I ask what year you were born? Or what century?”",
      },
      {
        type: "paragraph",
        text: "Participants soon discovered that the year was 2088; any disorientation they might be experiencing is the side effect of their recent revival from cryogenic sleep. \"Don't worry,\" Ellen reassured them. \"But instead of using this form, please just have a quick seat. You’ll need to interface with our in-house AI instead.\" On the other side of the curtain was PETAR, a tall blue box that looked like a two-screened arcade game. “Whenever you’re ready, just announce yourself, say hello, or give PETAR a light knock to begin,\" Ellen coached.",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/03-petar-console.webp",
        width: 1333,
        height: 2000,
        alt: "PETAR's console features two screens, with questions below and PETAR's conversational interface above. Or is the top one just a two-way mirror?",
        caption: "PETAR’s console features two screens, with questions below and PETAR’s conversational interface above. Or is the top one just a two-way mirror?",
      },
      {
        type: "paragraph",
        text: "When users spoke to PETAR, PETAR spoke back. He explained his name and overarching directive — “PETAR” stands for the Production and Economic Teleological Allocation Robot, and it’s his job to make sure that you’re fed, clothed, housed, and content — before quickly launching into a sorting conversation. PETAR’s first questions were challenging and introspective: “Are you more of a critical thinker or creative thinker?”, “Do you prefer interacting directly with people who need your help, or solving a problem at the conceptual or system level?”, he would ask. Next, participants had to decide between different continents and regions for their work placement. Each location was characterized by a different social, technological, environmental, or political trend that influenced the jobs available there.",
      },
      {
        type: "imageGrid",
        columns: 4,
        images: [
          { src: "/images/human-resourcing-dept/event-01.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-02.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-03.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-04.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-05.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-06.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-07.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-08.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-09.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-10.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-11.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-12.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-13.webp", width: 1333, height: 2000, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-14.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-15.webp", width: 2000, height: 1334, alt: "The Human Resourcing Dept. event in action" },
          { src: "/images/human-resourcing-dept/event-16.webp", width: 1333, height: 2000, alt: "The Human Resourcing Dept. event in action" },
        ],
      },
      {
        type: "paragraph",
        text: "By the time the questioning was complete, PETAR had determined the participant’s vocation — and spit it out as a sticker at the bottom of his box. With sticker in hand, participants returned to the front of the space, where Ellen carefully placed the sticker on a badge and gave participants an exit interview form to fill out. As participants left, they were urged to wear their ID badges for the next day, Ellen explaining, “You’ll be picked up by aerial drone in the next 24 hours to be taken to your new vocation, and the ID badge will help the drone locate you.”",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/09-posters.webp",
        width: 2000,
        height: 1334,
        alt: "Posters in the waiting area promote the different territories where PETAR could place participants.",
        caption: "Posters in the waiting area promote the different territories where PETAR could place participants.",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/10-logic-tree.webp",
        width: 2500,
        height: 5026,
        alt: "This model intends to distill all the possible permutations that PETAR's conversation could take — and the 36 different jobs at the end of each one.",
        caption: "This model intends to distill all the possible permutations that PETAR’s conversation could take — and the 36 different jobs at the end of each one.",
      },
      { type: "heading", level: 2, text: "Ideation" },
      {
        type: "paragraph",
        text: "In the course of my thesis research, I’d determined that workers would need to be adaptable and open to change if they wanted to come out of the AI Revolution with their personal agency intact. To emotionally introduce my audience to this unsettling future, I set out to design an experience that would take participants on an emotional arc: starting low, when they learned that their old skills were obsolete, and finishing high, once they had found a new sense of social purpose in 2088.",
      },
      {
        type: "paragraph",
        text: "Early on in the ideation process, I resolved that the takeaway for my experience would be a “job in the future.” I devised a framework for sorting participants into different worker personality types by turning the three core human qualities that I had uncovered in my research — critical thinking, creative thinking, and emotional intelligence — into two binaries on a two-by-two matrix.",
      },
      {
        type: "paragraph",
        text: "I then designed questions to assess which end of each spectrum a participant leaned toward. These questions weren’t truly binary dichotomies, (i.e. someone can be both a highly critical and creative thinker), but the difficulty some participants had in answering questions accurately reflected the emotions of choosing a profession and navigating a career today — so why should that completely change by 2088? With the personas established, the process of devising the nine future scenarios and 36 jobs was relatively straightforward.",
      },
      {
        type: "paragraph",
        text: "I had originally envisioned the experience as a coded game with video clips of PETAR incorporated throughout. But when I presented my wireframes and logic tree to a friend who works as a web developer, I learned that my time and budget constraints made this impossible. So I quickly changed course for an actor-in-a-box solution, which ultimately proved to be more delightful for the participant.",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/11-emotional-arc.webp",
        width: 2500,
        height: 1908,
        alt: "The emotional journey I hoped to take participants on.",
        caption: "The emotional journey I hoped to take participants on.",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/12-four-personas.webp",
        width: 2500,
        height: 1908,
        alt: "The four worker personas, based on relative prioritization of critical thinking, creative thinking, and emotional intuition.",
        caption: "The four worker personas, based on relative prioritization of critical thinking, creative thinking, and emotional intuition.",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/13-job-list.webp",
        width: 2500,
        height: 1407,
        alt: "Based on their persona type and the region and territories they opted for, participants ended up with one of these 36 jobs. They would receive this entire sheet as a final takeaway.",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "With the concept established, the development process was graphic design-intensive with an emphasis on branding.",
      },
      {
        type: "imageGrid",
        columns: 4,
        images: [
          { src: "/images/human-resourcing-dept/process-01.webp", width: 1080, height: 1080, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-02.webp", width: 1500, height: 2000, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-03.webp", width: 1500, height: 2000, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-04.webp", width: 1500, height: 2000, alt: "A moodboard for the Human Resourcing Dept.'s visual identity" },
          { src: "/images/human-resourcing-dept/process-05.webp", width: 2000, height: 1500, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-06.webp", width: 2500, height: 1563, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-07.webp", width: 1164, height: 1682, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-08.webp", width: 2000, height: 1707, alt: "Sketching the PETAR console box" },
          { src: "/images/human-resourcing-dept/process-09.webp", width: 1760, height: 2000, alt: "Measuring out the PETAR console box" },
          { src: "/images/human-resourcing-dept/process-10.webp", width: 2500, height: 1563, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-11.webp", width: 1500, height: 2000, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-12.webp", width: 1743, height: 2000, alt: "PETAR's branding" },
          { src: "/images/human-resourcing-dept/process-13.webp", width: 1572, height: 878, alt: "Designing the Human Resourcing Dept.'s branding and collateral" },
          { src: "/images/human-resourcing-dept/process-14.webp", width: 2000, height: 2000, alt: "The dedicated Instagram account's logo" },
          { src: "/images/human-resourcing-dept/process-15.webp", width: 2000, height: 2000, alt: "The Human Resourcing Dept.'s logo" },
          { src: "/images/human-resourcing-dept/process-16.webp", width: 2000, height: 2000, alt: "PETAR's logo" },
        ],
      },
      { type: "label", text: "Collateral" },
      {
        type: "paragraph",
        text: "I also had to develop an array of forms, worksheets, badges, stickers, posters and even magazines to complete the world of the Human Resourcing Dept.",
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/18-event-poster.webp",
        width: 1294,
        height: 2000,
        alt: "The event poster I used to promote my event",
        caption: "The event poster I used to promote my event.",
      },
      {
        type: "imageGrid",
        columns: 4,
        images: [
          { src: "/images/human-resourcing-dept/collateral-01.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-02.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-03.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-04.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-05.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-06.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-07.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-08.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-09.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-10.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-11.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
          { src: "/images/human-resourcing-dept/collateral-12.webp", width: 2000, height: 1334, alt: "Collateral developed for the Human Resourcing Dept." },
        ],
      },
      {
        type: "image",
        src: "/images/human-resourcing-dept/54-closing.webp",
        width: 2000,
        height: 1334,
        alt: "A participant interacts with PETAR",
      },
    ],
    closingBlocks: [
      {
        type: "paragraph",
        text: "The Human Resourcing Dept. was developed as part of my master’s thesis, *Me, Myself & A.I.: How I Learned to Love the Machine That Took my Job*. [You can watch my thesis video, read my thesis book, and see my other thesis projects here.](/archive/thesis) To see more documentation of the development process for this project, check out the [dedicated Instagram account](https://www.instagram.com/human_resourcing/).",
      },
    ],
  },
  jade: {
    slug: "jade",
    recognition: [],
    blocks: [
      { type: "heading", level: 2, text: "A smarter kind of elder care" },
      {
        type: "paragraph",
        text: "Jade is a wearable device designed to help the elderly remain independent for longer. When Jade notices a worrisome deviation from its wearer’s routine, the pendant vibrates to indicate that it’s concerned. Users can squeeze the pendant to let Jade know that everything is fine — but if they don’t, help will soon be on the way.",
      },
      // The original Vimeo embed (id 265844265) was taken down for music
      // copyright reasons, so this is self-hosted on R2 instead — a plain
      // file is never scanned/flagged the way a Vimeo/YouTube upload is.
      {
        type: "video",
        provider: "file",
        url: "https://pub-1e1e0e4d047847bbad37d4cf58fd6bab.r2.dev/jade-walk-in-the-park.mp4",
        caption: "Watch Jade in action.",
      },
      { type: "heading", level: 2, text: "Problem" },
      {
        type: "paragraph",
        text: "The elderly are the world’s fastest growing demographic. The number of people in the United States aged 65+ is expected to almost double by 2050, jumping from 43.1 million in 2012 (13.7% of the population) to a projected 83.7 million (20.9%). And globally, the shift will be even more dramatic, with the elderly population expected to swell from 617 million in 2015 to 1.6 billion in 2050 — an increase from 8.5% to 17% of the world population. Thanks to both improved medical science and better access to lifelong preventative care, people are living longer: the global average lifespan is expected to jump from 68.6 years in 2015 to 76.2 in 2050.",
      },
      {
        type: "paragraph",
        text: "So what will happen when the elderly make up almost a fifth of the world’s population? The newly elderly may find themselves frustrated by a society that expects them to be feebler or less sharp than they really are. Adult children who remember the physical and mental deterioration of their grandparents are likely to worry about their now-elderly parents living on their own. For elderly parents who enjoy their independence, but still want to allay their children’s worries, is there an acceptable compromise?",
      },
      { type: "heading", level: 2, text: "Solution" },
      {
        type: "image",
        src: "/images/jade/04-setup.webp",
        width: 2000,
        height: 1082,
        alt: "Jade's two-week setup period",
        caption: "For the first two weeks, the pendant gathers audio and GPS data to build a model of the wearer’s routine. Once the model is created, the wearer labels the important sounds and locations in their life to train the algorithm. But no one’s life is perfectly repetitive — so Jade is constantly updating its model based on its latest observations.",
      },
      {
        type: "image",
        src: "/images/jade/05-deviation.webp",
        width: 2000,
        height: 1082,
        alt: "Jade's pendant vibrating to express concern",
        caption: "When Jade detects a worrisome deviation from the routine — perhaps the wearer has been silent and stationary in an unusual place for a while — the pendant vibrates noisily to express its concern. If the user is fine, they can simply squeeze the pendant to silence it. But if they are unable to respond, help will soon be on the way.",
      },
      {
        type: "paragraph",
        text: "Jade is a hardware fix for retirees who want to remain independent and active while putting their fretful family at ease. It comes as a set of two smart objects: a wearable pendant for outside the house, and a charging stand to hold the pendant when they’re home. The pendant’s microphone and GPS sensors constantly listen to the wearer’s environment and monitor their whereabouts. (While this may sound potentially insidious, the Jade team never sells user data to third parties, deletes it routinely, and uses blockchain encryption to protect data that’s in use.) Jade uses this information to build a model of the wearer’s typical routine — where they go, how long they spend there, who they talk to, and how their voices sound — using a mixture of natural language processing and other deep learning AI techniques. If Jade senses a worrisome deviation from that routine (such as angry and distressed voices, or stationary silence in an unusual location), the pendant vibrates noisily with increasing intensity to express its concern to the wearer. If the wearer is fine, they can simply squeeze the pendant to stop the vibrations and reassure Jade that they’re alright. But if the wearer is unable to respond to the pendant’s vibrations within two minutes, Jade will alert their emergency contacts with a call and geotagged text messages.",
      },
      {
        type: "paragraph",
        text: "Besides charging the pendant’s sensors and decreasing the likelihood of loss, the stand serves a third purpose: sonar sight. While the location information provided by the GPS can track the whereabouts of Jade users outside the home, a much more refined view is required for identifying when the user falls or has an accident within the home. By bouncing inaudible sound waves into the home and listening for the return patterns, Jade builds a 3D model of the home’s interior — just like a bat uses echolocation to hunt in the dark — and can detect when the owner is in a worrisome position, like lying on the bathroom floor.",
      },
      {
        type: "paragraph",
        text: "Jade’s key competitive differentiation is its incorporation of intelligent automation in the process of calling for help. All of Life Alert’s products require the user to click a button and speak to a representative in the event of an emergency. But what if the user loses consciousness, and can’t perform this critical step to save themselves? And while there are a few competing products that use an accelerometer to automatically report a fall, they’re prone to false alarms when the wearer makes a sudden movement or simply lies down to sleep. Only Jade’s AI-informed model of the wearer’s routine offers a reliable means of providing automatic alerts.",
      },
      {
        type: "image",
        src: "/images/jade/07-app-screens.webp",
        width: 2000,
        height: 1126,
        alt: "Jade's companion app",
        caption: "Jade owners will mostly use the companion app to label Jade’s model of their routine and manage who gets alerts in an emergency. But they can also use it to view the data that Jade has collected or change the haptic control preferences (if squeezing the pendant is difficult for their hands).",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "The conception and refinement of Jade’s final shape was iteration-intensive, the early stages involving repeated oscillation between two- and three-dimensional sketching. The goal of my 3D design process was to develop a pleasing, aspirational aesthetic language — so users wouldn’t be embarrassed to wear the pendant as jewelry or mind setting the stand on display in their home. But the pendant also needed to be sturdy enough to withstand the bludgeoning of daily wear, so the form would have to be self-contained and not overly ornate.",
      },
      {
        type: "imageGrid",
        columns: 3,
        images: [
          { src: "/images/jade/g1-01-clamshell1.webp", width: 1644, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-02-clamshell2.webp", width: 1536, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-03-earrings1.webp", width: 1559, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-04-page1.webp", width: 1618, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-05-page2.webp", width: 1583, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-06-earrings2.webp", width: 1578, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-07-page3.webp", width: 1565, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-08-page6.webp", width: 1670, height: 2000, alt: "Jade branding and packaging exploration" },
          { src: "/images/jade/g1-09-page7.webp", width: 1545, height: 2000, alt: "Jade branding and packaging exploration" },
        ],
      },
      {
        type: "imageGrid",
        columns: 3,
        images: [
          { src: "/images/jade/g2-01.webp", width: 2000, height: 1500, alt: "Prototyping Jade's physical form" },
          { src: "/images/jade/g2-02.webp", width: 2000, height: 1500, alt: "Prototyping Jade's physical form" },
          { src: "/images/jade/g2-03.webp", width: 2000, height: 1500, alt: "Prototyping Jade's physical form" },
          { src: "/images/jade/g2-04.webp", width: 2000, height: 1500, alt: "Prototyping Jade's physical form" },
          { src: "/images/jade/g2-05.webp", width: 1500, height: 2000, alt: "Prototyping Jade's physical form" },
          { src: "/images/jade/g2-06.webp", width: 2000, height: 1500, alt: "Prototyping Jade's physical form" },
        ],
      },
      {
        type: "image",
        src: "/images/jade/11-process.webp",
        width: 2000,
        height: 972,
        alt: "Prototyping Jade's physical form",
      },
      {
        type: "image",
        src: "/images/jade/12-orthographic-exploration.webp",
        width: 2000,
        height: 1569,
        alt: "Orthographic exploration of Jade's form",
      },
      {
        type: "image",
        src: "/images/jade/13-orthographic.webp",
        width: 2000,
        height: 1552,
        alt: "Orthographic drawings of Jade's final form",
      },
      {
        type: "image",
        src: "/images/jade/14-rhino-screenshot.webp",
        width: 2500,
        height: 1645,
        alt: "3D modeling Jade's form in Rhino",
      },
      {
        type: "image",
        src: "/images/jade/15-process.webp",
        width: 2000,
        height: 1301,
        alt: "Prototyping Jade's physical form",
      },
      {
        type: "image",
        src: "/images/jade/16-process.webp",
        width: 1500,
        height: 2000,
        alt: "Prototyping Jade's physical form",
      },
      {
        type: "image",
        src: "/images/jade/17-process.webp",
        width: 2000,
        height: 1334,
        alt: "Prototyping Jade's physical form",
      },
      {
        type: "paragraph",
        text: "The brand identity is a reference to the stone, which is said to encourage peacefulness, relieve anxiety, and enhance good luck. The name is intended to convey an air of sophistication, rather than the clunky utilitarianism of a title like “Life Alert.” Inspiration for the exact shade of seafoam green was drawn from the classic cars of the 1950s and ‘60s, which embody the timeless cool of Jade’s target user.",
      },
      {
        type: "imageGrid",
        columns: 2,
        images: [
          { src: "/images/jade/g3-01-chevy-ad.webp", width: 656, height: 1316, alt: "A 1956 Chevrolet advertisement, a mood reference for Jade's color palette" },
          { src: "/images/jade/g3-02-mood.webp", width: 564, height: 564, alt: "A mood reference for Jade's brand identity" },
          { src: "/images/jade/g3-03-jade-stone.webp", width: 1500, height: 1125, alt: "A jade stone, the namesake and color reference for the brand" },
          { src: "/images/jade/g3-04-asset13.webp", width: 2000, height: 2000, alt: "Jade's brand identity system" },
        ],
      },
      {
        type: "image",
        src: "/images/jade/20-final.webp",
        width: 1546,
        height: 2000,
        alt: "The final Jade pendant and charging stand",
      },
      {
        type: "image",
        src: "/images/jade/21-colored-in-hand.webp",
        width: 2000,
        height: 1541,
        alt: "The final Jade pendant, held in hand",
      },
    ],
    closingBlocks: [
      {
        type: "paragraph",
        text: "Jade was developed as part of my master’s thesis, *Me, Myself & A.I.: How I Learned to Love the Machine That Took my Job*. [You can watch my thesis video, read my thesis book, and see my other thesis projects here.](/archive/thesis)",
      },
    ],
  },
  staygo: {
    slug: "staygo",
    recognition: [],
    blocks: [
      { type: "heading", level: 2, text: "The open road. On your terms." },
      {
        type: "paragraph",
        text: "StayGo is a service that gives truck drivers a chance to explore web-based opportunities from the open road. It does this by operating a fleet of semi-autonomous trucks with sleeper cabs that double as mobile offices, which it rents out to human drivers — so they can take online classes or pursue their own ventures while AI handles the highway driving. This helps drivers transition more gradually out of an industry which will soon depend less on human involvement, and helps the trucking industry retain and attract the drivers it needs while self-driving technology continues to be refined.",
      },
      {
        type: "image",
        src: "/images/staygo/02-mobile-office.webp",
        width: 2500,
        height: 1408,
        alt: "A StayGo truck cab's sleeper compartment, reimagined as a mobile office with a desk and monitor",
      },
      { type: "heading", level: 2, text: "Problem" },
      {
        type: "image",
        src: "/images/staygo/03-self-driving-lidar.webp",
        width: 1920,
        height: 1080,
        alt: "Self-driving cars are getting better every day, but are still years away from being able to reliably navigate the unpredictability of city streets.",
        caption: "Self-driving cars are getting better every day, but are still years away from being able to reliably navigate the unpredictability of city streets.",
      },
      {
        type: "paragraph",
        text: "In any list of jobs that are next on automation's chopping block, trucking is a commonly cited industry. It's easy to see why: with some of the world’s richest companies pouring money into driverless cars for the consumer market[1](https://www.reuters.com/article/us-autos-selfdriving-suppliers/self-driving-arms-race-complicates-supplier-alliances-idUSKBN17F0EZ), it stands to reason that people whose profession is over 66% driving[2](https://www.ncbi.nlm.nih.gov/books/NBK384974/) may soon be looking for different work.",
      },
      {
        type: "image",
        src: "/images/staygo/04-starsky-robotics.webp",
        width: 2000,
        height: 1125,
        alt: "Companies like Starsky Robotics are exploring how to partner human drivers with smarter trucks — but are still failing to consider the drivers' long-term prospects.",
        caption: "Companies like Starsky Robotics are exploring how to partner human drivers with smarter trucks — but are still failing to consider the drivers’ long-term prospects.",
      },
      {
        type: "paragraph",
        text: "But rumors of trucking's demise are greatly exaggerated — or at least accelerated. A closer look at the job's duties reveals a wide array of humanity-intensive tasks that aren’t so easily automated. Overseeing loading and unloading, refueling, mechanical maintenance, interacting with authorities — activities like these can occur unpredictably throughout a trucker’s day, and each contains thousands of sub-tasks and variations. This means that trucking companies will continue to rely on human experience and intuition to steward their cargo.",
      },
      {
        type: "paragraph",
        text: "Plus, while driverless tech has grown in leaps and bounds so far, AI companies are still years away from fully autonomous vehicles. AI may have mastered highway driving, but it turns out that getting cars to reliably self-navigate on pedestrian-filled city streets is a different challenge entirely.",
      },
      {
        type: "paragraph",
        text: "While truck drivers may not become completely obsolete in the next few years, AI still promises to change their lives and livelihoods — because their industry is already in turmoil. In 2017, the American Trucking Association reported a turnover rate of 81% and projected a shortage of 50,700 drivers for the coming year. In an industry that employs 3.5 million drivers (and 7.5 million people overall), those are worrying numbers — while competition continues to tighten its margins.[3](http://progressive2.acs.playstream.com/truckline/progressive/ATAs%20Driver%20Shortage%20Report%202017.pdf)",
      },
      {
        type: "paragraph",
        text: "Innovative companies are already exploring how they can partner human drivers with semiautonomous trucks to reap greater efficiencies: Uber Freight is planning a system that has local human drivers grab cargo from long-distance robot trucks at relay points, and Starsky Robotics is developing fleets of trucks that will be remotely piloted by a single driver whenever they exit the highway.[4](https://www.bloomberg.com/news/features/2017-06-22/these-truckers-work-alongside-the-coders-trying-to-eliminate-their-jobs) But while these concepts might improve the quality of life for a handful of drivers in the present, none of them prepare drivers for the jobs they might have a decade from now. That's where StayGo stands out from the competition.",
      },
      { type: "heading", level: 2, text: "Solution" },
      {
        type: "image",
        src: "/images/staygo/05-division-of-labor.webp",
        width: 2500,
        height: 1352,
        alt: "The truck drives itself on the highway, manages navigation, and prompts the driver when needed; the driver drives off the highway, oversees loading and unloading, and handles fueling and basic maintenance",
      },
      {
        type: "paragraph",
        text: "StayGo owns and operates a fleet of semi-autonomous sleeper cab trucks, each outfitted with a computer and high-speed internet. Shipping companies hire StayGo to run its routes just like they would hire a driver that owns his own truck. From there, StayGo rents out its truck routes to drivers interested in trying something new.",
      },
      {
        type: "paragraph",
        text: "The appeal for current truck drivers is clear: For a marginal pay cut (StayGo’s fee), drivers suddenly have hours of free time in the middle of their day to mine the Internet for new opportunities. Many drivers may already have an idea for a new web-based side hustle. And for those without an immediate plan, StayGo’s onboard terminal comes installed with third-party training resources like Skillshare, Lynda, and its own proprietary entrepreneurship curriculum.",
      },
      {
        type: "image",
        src: "/images/staygo/06-ted-1-duck-carving.webp",
        width: 2500,
        height: 1407,
        alt: "Ted Trucker is a duck decoy carving maestro — when his hands aren’t on the steering wheel.",
        caption: "Ted Trucker is a duck decoy carving maestro — when his hands aren’t on the steering wheel.",
      },
      {
        type: "image",
        src: "/images/staygo/07-ted-2-mobile-office.webp",
        width: 2500,
        height: 1408,
        alt: "StayGo’s mobile office and free online learning resources helped Ted turn his hobby into a business — including a pretty healthy YouTube following for his process videos.",
        caption: "StayGo’s mobile office and free online learning resources helped Ted turn his hobby into a business — including a pretty healthy YouTube following for his process videos.",
      },
      {
        type: "image",
        src: "/images/staygo/08-ted-3-business.webp",
        width: 2500,
        height: 1407,
        alt: "Now Ted can focus on growing his business, using the knowledge and resources he first explored while in the cab of his StayGo truck.",
        caption: "Now Ted can focus on growing his business, using the knowledge and resources he first explored while in the cab of his StayGo truck.",
      },
      {
        type: "image",
        src: "/images/staygo/09-ted-4-booking-ride.webp",
        width: 2500,
        height: 1407,
        alt: "But Ted still has the flexibility to book a ride with StayGo whenever he needs the extra cash — or even when he’s simply missing the open road.",
        caption: "But Ted still has the flexibility to book a ride with StayGo whenever he needs the extra cash — or even when he’s simply missing the open road.",
      },
      {
        type: "paragraph",
        text: "By changing the value proposition of a truck-driving career, StayGo won’t just improve the lives of current truck drivers — it will broaden the career’s appeal and expand the labor pool. There are already people with web-based careers who harbor a secret itch to experience a life on the open road. For many creative professionals, the private work environment offered by a StayGo truck’s mobile office is enough incentive to try something new. And for the rest, the promise of additional income and the chance to live as a professional tourist of North America’s beautiful landscape will be a powerful motivator. For this group, there will be an additional barrier to entry: training. But StayGo will work in close partnership with trucking companies and the American Trucking Association to develop a driving simulator, training curriculum and certification process that prepares aspirant truckers for the challenges of the open road.",
      },
      {
        type: "image",
        src: "/images/staygo/10-susan-1-writing.webp",
        width: 2500,
        height: 1407,
        alt: "Susan is a writer who’s feeling low on inspiration — and could use a break from the city clangor.",
        caption: "Susan is a writer who’s feeling low on inspiration — and could use a break from the city clangor.",
      },
      {
        type: "image",
        src: "/images/staygo/11-susan-2-ad.webp",
        width: 2500,
        height: 1407,
        alt: "An ad extolling the virtues of the open road catches Susan’s eye — so she signs up for training.",
        caption: "An ad extolling the virtues of the open road catches Susan’s eye — so she signs up for training.",
      },
      {
        type: "image",
        src: "/images/staygo/12-susan-3-training.webp",
        width: 2500,
        height: 1406,
        alt: "She’ll need to get licensed, first. But StayGo’s VR trucking training program is clear, easy — and even a bit fun.",
        caption: "She’ll need to get licensed, first. But StayGo’s VR trucking training program is clear, easy — and even a bit fun.",
      },
      {
        type: "image",
        src: "/images/staygo/13-susan-4-booking-ride.webp",
        width: 2500,
        height: 1407,
        alt: "Now Susan can book a ride with StayGo whenever she begins to miss the peace and solitude of the open road.",
        caption: "Now Susan can book a ride with StayGo whenever she begins to miss the peace and solitude of the open road.",
      },
      {
        type: "image",
        src: "/images/staygo/14-ecosystem.webp",
        width: 2500,
        height: 1407,
        alt: "StayGo takes a portion of the driver's fee, much like a temp agency. In return, the driver gets back hours of each day to invest in his or her future.",
        caption: "StayGo takes a portion of the driver’s fee, much like a temp agency. In return, the driver gets back hours of each day to invest in his or her future.",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "The concept development process was reflective, iterative and collaborative. It began by writing out what felt like the most urgent need states for the target group, then interrogating their validity (and underlying cause) through an asking of the “Five Whys.” I repeated this process until I arrived at a set of need statements that felt both actionable and incapable of being broken down any further. From there, I used these statements as provocations in a group brainstorming exercise in which classmates sketched out their initial ideas on post-it notes. After this exercise, I sorted these short ideas into related directions, picked the most promising category and looked to turn my classmates’ short suggestions into a fuller concept. And thus, StayGo was born.",
      },
      {
        type: "image",
        src: "/images/staygo/15-process-five-whys-1.webp",
        width: 2500,
        height: 1535,
        alt: "A notebook page asking the “Five Whys” about people's need to find meaning outside of work",
      },
      {
        type: "image",
        src: "/images/staygo/16-process-five-whys-2.webp",
        width: 2500,
        height: 1538,
        alt: "A second notebook page continuing the “Five Whys” exercise",
      },
      {
        type: "image",
        src: "/images/staygo/17-process-sorting-1.webp",
        width: 2500,
        height: 3333,
        alt: "A whiteboard covered in colorful post-it notes, sorting classmates' brainstormed ideas into related directions",
      },
      {
        type: "image",
        src: "/images/staygo/18-process-sorting-2.webp",
        width: 2500,
        height: 1875,
        alt: "Classmates sorting brainstormed post-it notes into related directions on a library bookshelf",
      },
    ],
    closingBlocks: [
      {
        type: "paragraph",
        text: "StayGo was developed as part of my master’s thesis, *Me, Myself & A.I.: How I Learned to Love the Machine That Took my Job*. [You can watch my thesis video, read my thesis book, and see my other thesis projects here.](/archive/thesis)",
      },
    ],
  },
  "water-token": {
    slug: "water-token",
    recognition: [],
    blocks: [
      { type: "heading", level: 2, text: "the water token project" },
      {
        type: "paragraph",
        text: "The Water Token Project is a cryptocurrency basic income program designed to create a more equitable distribution of water. Outlined as a policy proposal for the state of California, a notoriously problematic and overextended watershed, the Water Token Project uses an array of machine learning algorithms to constantly recalculate the gallon-value of a water token on a monthly basis and sustainably distribute these tokens to corporations and citizens alike.",
      },
      {
        type: "image",
        src: "/images/water-token/02-ad-mockup.webp",
        width: 1794,
        height: 1266,
        alt: "An early awareness ad for the initiative, touting the importance of water efficiency.",
        caption: "An early awareness ad for the initiative, touting the importance of water efficiency.",
      },
      {
        type: "quote",
        text: "“Water, water, everywhere, Nor any drop to drink.” —Samuel Taylor Coleridge, *The Rime of the Ancient Mariner*",
      },
      { type: "heading", level: 2, text: "Background" },
      {
        type: "paragraph",
        text: "Water covers 71% of the planet, so how can it be scarce? Only 2.5% of the Earth’s water is fresh water, meaning it’s salt-free enough for human consumption. Most of that fresh water—68%—is ice, frozen in Earth’s polar ice caps. 30% is ground water, trapped in underground aquifers. The remaining 2% of that fresh water is surface water—that’s the water in streams, lakes, and atmosphere. Remember the water cycle from grade school, where evaporation creates clouds that fall as rain, over and over again? That’s surface water.",
      },
      {
        type: "paragraph",
        text: "Unfortunately, reality is never as orderly and simple as it appears on a primary school chalkboard. And humans are currently using, polluting and depleting the planet’s fresh surface water far faster than the water cycle can replenish it.",
      },
      {
        type: "image",
        src: "/images/water-token/03-water-cycle.webp",
        width: 2500,
        height: 1407,
        alt: "The water cycle is how surface water—the fresh water in lakes, streams and permafrost—is replenished over time. But it's only 2% of the water on Earth. And we're using it way too fast.",
        caption: "The water cycle is how surface water—the fresh water in lakes, streams and permafrost—is replenished over time. But it’s only 2% of the water on Earth. And we’re using it way too fast.",
      },
      {
        type: "paragraph",
        text: "How are we using it? While it’s true that most of us could stand to cut back on the length of our showers, domestic plumbing makes up just 11% of water use. Industrial use—that’s water used for cooling and production processes—takes up another 19%. The remaining 70% is agricultural use, with animal farming the most water-intensive production process by far (due to all the water that goes into producing the food the animal eats and watering the animal itself).",
      },
      {
        type: "paragraph",
        text: "For the most part, we have always treated water as a limitless resource. As a result, we’re experiencing a tragedy of the commons: lack of ownership and responsible allocation has created imminent shortages around the world, starting with the most arid regions—many of which are anticipated to expand as climate change’s effects unfold. On a global scale, the prognosis is clear: our current water use is dangerously unsustainable.",
      },
      {
        type: "image",
        src: "/images/water-token/04-arjen-hoekstra.webp",
        width: 966,
        height: 966,
        alt: "Arjen Hoekstra, who developed the water footprint concept and assessment process.",
        caption: "Arjen Hoekstra, who developed the water footprint concept and assessment process.",
      },
      {
        type: "paragraph",
        text: "To help governments manage and plan water use, a research team led by Arjen Hoekstra, a professor of water management at the University of Twente, developed the concept of a “water footprint” in 2012. A water footprint looks at both direct and indirect freshwater use, enabling auditors to evaluate the impact of a product’s entire supply chain. The concept’s potential applications are broad, but Hoekstra advocates for the creation of footprint caps for water basins and footprint benchmarks for product categories as a means of structuring and enforcing efficient water use.",
      },
      {
        type: "paragraph",
        text: "While it’s a powerful concept, water footprint assessments have a few key limitations. First, one footprint assessment can’t reveal the tradeoffs associated with key water usage decisions—that would require comparing multiple assessments from before and after policy changes. And second, manual data collection and analysis are time-consuming processes, which makes the creation of multiple comparative studies expensive and unlikely (and also increases the likelihood of human error).",
      },
      {
        type: "paragraph",
        text: "If only there were some way to automate the process, with key data sources constantly flowing into live, predictive models…",
      },
      { type: "heading", level: 2, text: "California" },
      {
        type: "paragraph",
        text: "Since the 1970s, California’s population has grown at a rate of 1.4% each year, while its water footprint was grown at more than double that rate: 4% each year. The water footprint of the state has long since eclipsed sustainable proportions, currently double that annual flow of the state’s two largest rivers, the Sacramento and San Joaquin. As such, 76% of the state’s water is imported through irrigation and product-embedded water (also known as “virtual water”), leaving the bulk of its agriculture dependent on direct rainwater—a precarious strategy in such an arid state. Additionally, California’s domestic allocation is intrinsically inequitable. Wealthier households use far more water than their low-income counterparts, in part due to their higher consumption of more water-intensive products (like meat).",
      },
      {
        type: "paragraph",
        text: "All signs point to the conclusion that California’s current water valuation paradigm is inadequate, simultaneously disempowering the state’s poorest residents and charting a course for state-wide crisis as climate change’s unpredictable impacts loom. In response, the Water Token Project was formed.",
      },
      {
        type: "image",
        src: "/images/water-token/05-water-footprint-income.webp",
        width: 1558,
        height: 986,
        alt: "The trend is simple: the richer you are, the more water you use.",
        caption: "The trend is simple: The richer you are, the more water you use. Source: Trends and Variation in California’s Water Footprint, CA Dept of Water Resources; US Environmental Protection Agency; Pacific Institute; UC Davis. 15 December 2013.",
      },
      {
        type: "image",
        src: "/images/water-token/06-what-if.webp",
        width: 2500,
        height: 1407,
        alt: "What if we developed an AI-regulated cryptocurrency for water distributed in a hydrologic zone: a water token — a universal system of allocating water access based on an aggregate score of need and potential",
      },
      { type: "heading", level: 2, text: "Vision" },
      {
        type: "paragraph",
        text: "The Water Token Project is a cap-and-trade program for water use in the state of California, coupled with the advanced capabilities of Ai algorithms to predict future value and recommend strategic investments.",
      },
      {
        type: "paragraph",
        text: "Each census-verified household is allotted one water token per resident each month. This virtual currency automatically “pays for the water they use each month. If a household exceeds their water allotment for the month (i.e. “runs out of water tokens before the 31st”), their account automatically buys surplus water tokens from the state’s Water Bank. Conversely, residents who do not use all their tokens each month can sell this surplus via the bank, transforming their unused water as a supplemental income for the household.",
      },
      {
        type: "paragraph",
        text: "The gallon-value of one water token is constantly recalculated by a family of powerful machine learning algorithms, based on a comprehensive array of real-time data sets: meteorological, ground water deposits, economic trends, consumption rates, and more. The token value is designed to create a generous apportionment of water for all private citizens, but can be controlled more strategically in its corporate distribution.",
      },
      {
        type: "paragraph",
        text: "The Water Bank determines how many tokens are invested in businesses each month based on multiple factors: industry benchmarks for water-efficient production in that sector; economic value of a crop or product to state GDP (measured in dollars-per-gallon); and projected growth potential for that business or industry. This level of scrutiny was impossible in the pre-AI era, but thankfully the Water Bank staff are able to lean on the recommendations of a tiered AI network that simultaneously evaluates the state economy and climate on a macro level, specializes in different industries and product categories on an intermediate level, and oversees the inputs and potential of individual businesses on the very micro level.",
      },
      {
        type: "paragraph",
        text: "Commercial allocation of tokens is also delivered with best-practice suggestions for water-efficient production in order to meet the Water Bank’s industry benchmarks, which may at first seem stringent to some companies. Additional counseling is available, especially in some instances where the bank thinks a company or farm may better serve the state by switching to a different product.",
      },
      {
        type: "paragraph",
        text: "In the immediate term, the Water Token Project should increase income for low-income households by enabling them to sell their excess tokens at the water bank and simultaneously increase the costs for excessive domestic water use (causing wealthier households to think twice before installing a second pool). In the medium term, the embedded expense of water tokens will increase the cost of high water footprint-products like meat, causing them to be priced like the luxuries they actually are. In the long term, this effect should use market forces to push Californians toward more water-efficient products and services, and guide the state to a sustainable pattern of water consumption.",
      },
      {
        type: "image",
        src: "/images/water-token/07-enabling.webp",
        width: 2500,
        height: 1407,
        alt: "Enabling benchmark enforcement, strategic investment, and equitable distribution",
      },
      { type: "heading", level: 2, text: "How it works" },
      {
        type: "paragraph",
        text: "Let’s see the system in action through three examples: the Joneses, a wealthy family; the Browns, a low-income family, and Vynes Vineyards, a small farm. First, here’s their average monthly water consumption:",
      },
      {
        type: "image",
        src: "/images/water-token/08-joneses-use.webp",
        width: 2500,
        height: 1407,
        alt: "The Joneses' pool and lawn makes for a high per capita water withdrawal each month.",
        caption: "The Joneses’ pool and lawn makes for a high per capita water withdrawal each month.",
      },
      {
        type: "image",
        src: "/images/water-token/09-browns-use.webp",
        width: 2500,
        height: 1407,
        alt: "The Browns have no pool or lawn, and thus use significantly less water.",
        caption: "The Browns have no pool or lawn, and thus use significantly less water.",
      },
      {
        type: "image",
        src: "/images/water-token/10-vynes-use.webp",
        width: 2500,
        height: 1407,
        alt: "In the growing season, Vynes Vineyards' single acre needs 29,000 gallons each month. If there's no local rainfall, it all has to come from the tap.",
        caption: "In the growing season, Vynes Vineyards’ single acre needs 29,000 gallons each month. If there’s no local rainfall, it all has to come from the tap.",
      },
      {
        type: "paragraph",
        text: "Normally, the Joneses simply pay more to get more. But in our new system, domestic tokens are allotted per resident—meaning you get one token per person per month. Commercial tokens are strategically invested based on industry production benchmarks and the economic value of the crop or product (measured in $ per gallon), and generally come with production best practices and other suggestions (like an alternative crop to grow for a low-GDP impact farm). Let’s see what happens in a month when water tokens are valued at 4,000 gallons:",
      },
      {
        type: "image",
        src: "/images/water-token/11-joneses-pay.webp",
        width: 2500,
        height: 1407,
        alt: "The Joneses go over their per-person allotment by 1,750 gallons this month. While the first 4,000 gallons are free, they must buy the remainder from The Water Bank.",
        caption: "The Joneses go over their per-person allotment by 1,750 gallons this month. While the first 4,000 gallons are free, they must buy the remainder from The Water Bank.",
      },
      {
        type: "image",
        src: "/images/water-token/12-browns-pay.webp",
        width: 2500,
        height: 1407,
        alt: "The Browns finish the month with 1,000 gallons to spare, each. Due to their efficiency, they can turn a profit by selling the rest of their tokens through The Water Bank.",
        caption: "The Browns finish the month with 1,000 gallons to spare, each. Due to their efficiency, they can turn a profit by selling the rest of their tokens through The Water Bank.",
      },
      {
        type: "image",
        src: "/images/water-token/13-vynes-pay.webp",
        width: 2500,
        height: 1410,
        alt: "The Water Bank over-allocates tokens to Vynes Vineyards because it thinks they should invest in developing their unused land, as grapes and wind are a water-profitable crop for California.",
        caption: "The Water Bank over-allocates tokens to Vynes Vineyards because it thinks they should invest in developing their unused land, as grapes and wind are a water-profitable crop for California. It’s up to Vynes to decide what to do with the profits from selling those extra 7.75 tokens!",
      },
      {
        type: "paragraph",
        text: "Everyone will experience either a token surplus or deficit every month. The difference is traded on The Water Bank, a digital marketplace where citizens and corporations can buy and sell unused tokens.",
      },
      {
        type: "paragraph",
        text: "Some businesses will be like Vynes, lucky to already be on the right track from a water efficiency standpoint. But those currently producing a water-inefficient crop or good will get production best practice tips and crop/product alternatives if they've picked a long-term loser. Token allocations will also be practically weaned down so as not to cause an overnight collapse as the company is forced to pivot.",
      },
      {
        type: "paragraph",
        text: "While the benefits of such a system will be immense in the long run, the behavior change demanded in the short term may be frustrating and intimidating for citizens and businesses. Effectively communicating the motivations behind the system through an awareness campaign will be critical in forestalling frustration and resentment.",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "While the concept of a water-based cryptocurrency began as a loose idea in a sea of speculative sketches, it was exciting to watch as its plausibility and validity continuously rose during the research process. Developing a theory of change map was instrumental in identifying the key assumptions inherent in the proposition worthy of greater exploration.",
      },
      {
        type: "image",
        src: "/images/water-token/14-theory-of-change.webp",
        width: 2500,
        height: 1407,
        alt: "This theory of change map was completed by starting with the overarching goal and working backwards—then filling in the key assumptions at each stage.",
        caption: "This theory of change map was completed by starting with the overarching goal and working backwards—then filling in the key assumptions at each stage.",
      },
      {
        type: "paragraph",
        text: "Once the gaps were identified, it was time to start sketching a prototyping.",
      },
      {
        type: "image",
        src: "/images/water-token/15-process-desalination-bacteria.webp",
        width: 1173,
        height: 1174,
        alt: "A speculative sketch for “Desalinating Bacteria” — bio-engineered, AI-assisted salt-eating microorganisms that can purify large amounts of water",
      },
      {
        type: "image",
        src: "/images/water-token/16-process-resource-conflict-mediation.webp",
        width: 1229,
        height: 1229,
        alt: "A speculative sketch for a “Resource Conflict Mediation” agency, a specialized legal entity that intercedes when critical resources like water get scarce",
      },
      {
        type: "image",
        src: "/images/water-token/17-process-ai-water-agency.webp",
        width: 1466,
        height: 1466,
        alt: "A sketch for an “A.I. Water Agency & Allocator,” which allocates water to different polities at different rates via an algorithm based on a composite score of population, production, and social contribution",
      },
      {
        type: "image",
        src: "/images/water-token/18-process-insert-for-water.webp",
        width: 2500,
        height: 1875,
        alt: "A cardboard coin-slot prototype reading “Insert for Water,” mocked up over a kitchen faucet",
      },
      {
        type: "image",
        src: "/images/water-token/19-process-produce-scale.webp",
        width: 2500,
        height: 1875,
        alt: "A cardboard prototype of a produce scale reading “Place produce on scale... Take your credit,” with real produce on top",
      },
      {
        type: "image",
        src: "/images/water-token/20-process-water-bank-logo.webp",
        width: 1291,
        height: 1291,
        alt: "An early lettering sketch for “The Water Bank” logo",
      },
      {
        type: "image",
        src: "/images/water-token/21-process-aquacoin-branding.webp",
        width: 2500,
        height: 2499,
        alt: "Branding exploration for the water token itself, including an early “aquacoin” name and various wave and water-molecule iconography",
      },
      {
        type: "image",
        src: "/images/water-token/22-process-token-cad.webp",
        width: 1524,
        height: 1524,
        alt: "A CAD model of the water token coin, embossed with a wave pattern",
      },
      {
        type: "image",
        src: "/images/water-token/23-process-token-final.webp",
        width: 1274,
        height: 1275,
        alt: "The final 3D-rendered water token, embossed with The Water Bank's wave logo",
      },
    ],
    closingBlocks: [
      {
        type: "paragraph",
        text: "The Water Token Project was developed as part of my master’s thesis, *Me, Myself & A.I.: How I Learned to Love the Machine That Took my Job*. [You can watch my thesis video, read my thesis book, and see my other thesis projects here.](/archive/thesis)",
      },
    ],
    sourceLink: {
      label: "this project's write-up on the Products of Design website",
      href: "https://productsofdesign.sva.edu/blog/water-token-project",
    },
  },
  classmates: {
    slug: "classmates",
    recognition: [],
    blocks: [
      { type: "heading", level: 2, text: "Turning soul-searching into a conversation." },
      {
        type: "paragraph",
        text: "Classmates is a mobile app that guides young professionals through a career switch. The app is designed to do two things for its users: introduce them to alternative jobs they might find appealing, and connect them to learning resources and people that will help them begin their new career.",
      },
      {
        type: "image",
        src: "/images/classmates/02-stat-graphic.webp",
        width: 2500,
        height: 1407,
        alt: "1 in 2 Americans feel emotionally detached from their career.",
      },
      { type: "heading", level: 2, text: "Problem" },
      {
        type: "image",
        src: "/images/classmates/03-low-cost-landscape.webp",
        width: 2500,
        height: 2333,
        alt: "While there are many resources for job-changers, they're either for people who are already qualified for a job, or for people who know what they need to learn to get there. What about everyone else?",
        caption: "While there are many resources for job-changers, they're either for people who are already qualified for a job, or for people who know what they need to learn to get there. What about everyone else?",
      },
      {
        type: "paragraph",
        text: "Automation could force up to 800 million people to switch occupations by 2030.[1](https://www.mckinsey.com/~/media/McKinsey/Global%20Themes/Future%20of%20Organizations/What%20the%20future%20of%20work%20will%20mean%20for%20jobs%20skills%20and%20wages/MGI-Jobs-Lost-Jobs-Gained-Report-December-6-2017.ashx) But even before the sea change that the AI Revolution may bring, we're already in the midst of a career-change crisis. More than half of American workers are emotionally detached from their work, with 55% of private sector workers describing their job as “just what they do for a living.”[2](http://www.pewsocialtrends.org/2016/10/06/3-how-americans-view-their-jobs/) In a country that prides itself on the belief that anyone with the right work ethic can do and become anything they want, why is worker dissatisfaction so high?",
      },
      {
        type: "paragraph",
        text: "Society pressure kids to specialize and succeed as early as possible. But when they get to the workforce, many are disappointed with the path they’re on. And Millennials — the largest and fastest-growing generation in the US workforce — are more likely to demand a sense of purpose from their work than previous generations. So if half of the 56 million millennials working today are dissatisfied…that’s a potential market of 28 million people.[3](https://www.cbsnews.com/news/why-so-many-americans-hate-their-jobs/)",
      },
      {
        type: "paragraph",
        text: "For those who want a change, the real question is: *how do I start?* Especially if they’re financially dependent on their current job. There are many inexpensive resources for both job-seekers and knowledge-seekers — but there’s a big gap between them. And none of these low-cost resources leverage the power of the group, or peer learning — one of the biggest selling points of in-person classes. So, ignoring the idea of ‘group job-seeking’ as nonsensical, I focused on group learning that segues to the job hunt and developed Classmates, Your guide to the wild world of online education.",
      },
      {
        type: "video",
        provider: "vimeo",
        id: "272838565",
      },
      { type: "heading", level: 2, text: "Solution" },
      {
        type: "paragraph",
        text: "Classmates helps users identify jobs they might be interested in, and discover the learning resources required to build skills associated with those jobs. And Classmates augments the existing ecosystem of online courses with its ‘Classrooms,’ where smaller groups of new learners can connect and share tips and resources.",
      },
      {
        type: "paragraph",
        text: "In an informal survey of 19 young professionals, 84% cited a preference for in-person education. They said it was because they found it easier to learn and stay motivated as part of a group. But two said they preferred online. Both had taken classes to begin a career path adjustment, and preferred online because of the flexibility it afforded — they could learn on their own schedule. What Classmates does is combine the flexibility of online with the community of in-person.",
      },
      {
        type: "video",
        provider: "vimeo",
        id: "273556139",
      },
      {
        type: "paragraph",
        text: "Classmates is free for users, and makes money through: partnerships with paid education platforms that give us a “finder’s fee” for students, and targeted ads in our classrooms. This revenue will help us keep growing and serve our bigger agenda: to prepare workers for the necessity of career transition that automation may bring.",
      },
      {
        type: "paragraph",
        text: "The jobs of the future will rely on critical thinking, creative thinking, and emotional intuition — so Classmates recommends careers that use these skills. And while it’s impossible to predict what new jobs may emerge as the economy transforms, there are service-oriented vocations that we believe communities will always need.",
      },
      {
        type: "image",
        src: "/images/classmates/04-screen-array.webp",
        width: 2500,
        height: 1052,
        alt: "Classmates' chat-based onboarding, job/skill/course recommendations, and classroom screens",
      },
      { type: "heading", level: 2, text: "Process" },
      {
        type: "paragraph",
        text: "I began by using a post-it intensive technique called “scenario mapping” to sketch out how my two user personas — the “old dog” and “young pup” — might interact with a piece of software designed to help them find a new job. By calling out the questions that might arise for a user at each stage, I was able to quickly create an extensive list of potential features for my final design proposal.",
      },
      {
        type: "image",
        src: "/images/classmates/05-scenario-map.webp",
        width: 2500,
        height: 1875,
        alt: "One of my second-phase scenario maps. Pink denotes a user interaction, green represents a potential issue or question that might arise at this juncture, and blue post-its are possible features or solutions.",
        caption: "One of my second-phase scenario maps. Pink denotes a user interaction, green represents a potential issue or question that might arise at this juncture, and blue post-its are possible features or solutions.",
      },
      {
        type: "paragraph",
        text: "Next, I created an online survey to interrogate my assumptions about user behavior and learn more about their experience with adult learning classes. It received 19 responses, with a median age of 26 — the sweet spot for my target demographic. As expected, almost all of them had changed jobs in the past 2 years — 84% — and 26% had done so in the past 6 months. The most common reasons for a job change were the pursuit of better opportunities for learning, growth, and fulfillment. All this confirmed what I had already suspected, and which my secondary research had suggested: millennials change work frequently because they put their own goals and values before the plans of any one company.",
      },
      {
        type: "imageGrid",
        columns: 3,
        images: [
          { src: "/images/classmates/g1-01-survey-overview.webp", width: 1920, height: 1080, alt: "Survey overview: an online survey format, 19 respondents, median age 26, across a range of occupations" },
          { src: "/images/classmates/g1-02-key-findings.webp", width: 1920, height: 1080, alt: "Key findings: millennials change jobs often, seeking fulfillment and growth, with a strong preference for in-person classes" },
          { src: "/images/classmates/g1-03-questions-opportunities.webp", width: 1920, height: 1080, alt: "Open questions and opportunities raised by the survey findings" },
        ],
      },
      {
        type: "paragraph",
        text: "Respondents’ relationships with adult learning classes were more complex. Many of those who had taken classes had done so in order to prepare for a career move, but a handful had also taken classes simply for the pleasure of a creative outlet. (It remains unclear if those represent different needs and user types, or different expressions of the same professional dissatisfaction.) 84% of respondents said that they would prefer to take a class that met in person, explaining that they were motivated to learn and retained information better when surrounded by peers and interacting with an instructor. But only 58% of respondents had actually taken a course since college — a discrepancy that suggests Classmates may need to overcome a negative perception bias around online courses in order to be successful. Interestingly, two respondents who had taken in-person courses to begin a career change actually said that they would have preferred if those classes had been online, because of the greater flexibility an online course affords.",
      },
      {
        type: "paragraph",
        text: "All these insights were useful when developing the app’s final architecture, but especially when crafting the tone and flow of the introductory CUI chat. When creating a system to sort users into areas of interest, it’s helpful to remain mindful of the varying goals and biases that your users may be bringing to the table.",
      },
      {
        type: "imageGrid",
        columns: 3,
        images: [
          { src: "/images/classmates/g2-01-young-pup-persona.webp", width: 2500, height: 2861, alt: "The “Young Pup” persona: Suzy Lawyer, Jr., a 28-year-old go-getter based in Washington, D.C." },
          { src: "/images/classmates/g2-02-ideation-post-its.webp", width: 2500, height: 3333, alt: "Early ideation post-its, including a sketch of the app's onboarding flow" },
          { src: "/images/classmates/g2-03-user-journey.webp", width: 2483, height: 2490, alt: "A hand-drawn user journey mapping the app's greeting/sorting, search/listings, recommended skills, and profile/résumé screens" },
          { src: "/images/classmates/g2-04-jobby-sketch-1.webp", width: 2500, height: 1962, alt: "Early wireframe sketches for Jobby (Classmates' working title), covering onboarding and job/skill recommendations" },
          { src: "/images/classmates/g2-05-jobby-sketch-2.webp", width: 2500, height: 1967, alt: "Early wireframe sketches for Jobby's classroom/forum screens" },
          { src: "/images/classmates/g2-06-greeting-wireframes.webp", width: 2500, height: 1931, alt: "Wireframe alternatives for the app's greeting and sorting screen" },
          { src: "/images/classmates/g2-07-profile-wireframes.webp", width: 2500, height: 1804, alt: "Wireframes for the app's profile builder flow" },
          { src: "/images/classmates/g2-08-search-wireframes.webp", width: 2500, height: 1895, alt: "Wireframes for the app's job search and listing screens" },
          { src: "/images/classmates/g2-09-training-wireframes.webp", width: 2480, height: 2409, alt: "Wireframes for the app's skill-training recommendation screens" },
          { src: "/images/classmates/g2-10-chatbot-mockups.webp", width: 2052, height: 1552, alt: "Higher-fidelity mockups of the app's conversational onboarding chatbot" },
          { src: "/images/classmates/g2-11-jobby-wireframes-sketch.webp", width: 2500, height: 1563, alt: "A Sketch file showing the Jobby prototype's onboarding and job-search screens" },
          { src: "/images/classmates/g2-12-classmates-wireframes-overview.webp", width: 2500, height: 1563, alt: "A Sketch file showing the full set of Classmates wireframes, from onboarding through the classroom feature" },
        ],
      },
      {
        type: "image",
        src: "/images/classmates/13-paper-prototype.webp",
        width: 2500,
        height: 1875,
        alt: "Paper prototyping is a quick and easy way to get user feedback without burning hours in Sketch and Flinto.",
        caption: "Paper prototyping is a quick and easy way to get user feedback without burning hours in Sketch and Flinto.",
      },
    ],
    closingBlocks: [
      {
        type: "paragraph",
        text: "Classmates was developed as part of my master’s thesis, *Me, Myself & A.I.: How I Learned to Love the Machine That Took my Job*. [You can watch my thesis video, read my thesis book, and see my other thesis projects here.](/archive/thesis)",
      },
    ],
  },
};
