import type { Project } from "@/content/types";

// Intro block at the top of the Work page.
export const workIntro = {
  title: "Skills and projects",
  description:
    "Here are the main design skills, modalities, and frameworks I employ to put my approach into practice — and select projects that showcase them.",
  skills: [
    "UI",
    "UX",
    "agentic dev",
    "design systems",
    "user research",
    "visual design",
    "AI/ML",
    "0->1",
  ],
};

export const projects: Project[] = [
  {
    slug: "my-transit-dashboard",
    company: "My /spec",
    logo: "/images/logo-myspec.svg",
    logoAlt: "My /spec",
    logoAspect: 116.059 / 34.5459,
    headline: "Live schedules for any MTA station at a single URL",
    body: "Built with Claude Code, [My Transit Dashboard](https://mta-transit-dashboard.vercel.app/) is a customizable tracker for MTA train and bus times — so I can check my top stations in a single step.",
    tags: ["agentic dev", "UX", "0->1"],
    hero: {
      alt: "My Transit Dashboard showing live MTA train and bus arrivals",
      artwork: {
        desktop: [
          {
            src: "/images/mta-spec-artwork.png",
            aspect: 3572 / 2258,
            height: "95%",
            top: "2.5%",
            left: "0%",
            rotate: 0,
          },
        ],
        mobile: [
          {
            src: "/images/mta-spec-artwork.png",
            aspect: 3572 / 2258,
            height: "125%",
            top: "8%",
            left: "3%",
            rotate: 0,
          },
        ],
      },
    },
    cta: {
      label: "Read more",
      href: "https://substack.com/home/post/p-199629367",
      external: true,
    },
  },
  {
    slug: "metamorph",
    company: "Pienso",
    logo: "/images/logo-pienso.svg",
    logoAlt: "Pienso",
    logoAspect: 139.034 / 32,
    headline: "Automated deep-learning training that informs and delights",
    body: "Metamorph is deep learning training interface that tracks model quality in real time so users can spot issues early and take corrective action.",
    tags: ["UI", "UX", "AI/ML", "0->1"],
    hero: {
      alt: "Metamorph deep-learning training interface with live model scoring",
      artwork: {
        desktop: [
          {
            src: "/images/metamorph-cards.png",
            aspect: 3576 / 2048,
            height: "74%",
            top: "25%",
            left: "0%",
            rotate: -15,
          },
        ],
        mobile: [
          {
            src: "/images/metamorph-cards.png",
            aspect: 3576 / 2048,
            height: "100%",
            top: "5%",
            left: "12%",
            rotate: 15,
          },
        ],
      },
    },
    cta: {
      label: "Read more",
      href: "https://www.figma.com/slides/lTENMJVJm78AlJZdRlTwx6",
      external: true,
    },
  },
  {
    slug: "match",
    company: "Pienso",
    logo: "/images/logo-pienso.svg",
    logoAlt: "Pienso",
    logoAspect: 139.034 / 32,
    headline: "Powerful text search that matches meaning, not just key words",
    body: "Match is a semantic search tool that gives users close control for finding sentences and documents with similar meaning.",
    tags: ["UI", "UX", "AI/ML", "0->1"],
    hero: {
      alt: "Match semantic search interface with example phrases and documents",
      artwork: [
        {
          src: "/images/match-screenshot.png",
          aspect: 3456 / 1856,
          height: "160.815%",
          top: "8%",
          left: "5%",
          rotate: 2.19,
          rounded: "7.2px",
          shadow: "0px 4px 4px 0px rgba(0,0,0,0.25)",
          unoptimized: true,
        },
      ],
    },
    cta: {
      label: "Read more",
      href: "https://www.figma.com/slides/UkPMbG7q7lNxEU3AJqiVRT",
      external: true,
    },
  },
  {
    slug: "extraction-demo",
    company: "Pienso",
    logo: "/images/logo-pienso.svg",
    logoAlt: "Pienso",
    logoAspect: 139.034 / 32,
    headline: "Rapidly unblocking channel sales to unlock the IDP market",
    body: "We designed a demo tool to show off Pienso’s new invoice extraction capabilities — in under a week.",
    tags: ["UX", "0->1", "design sprint", "leadership"],
    hero: {
      alt: "Invoice documents with automatically extracted fields",
      artwork: {
        desktop: [
          {
            src: "/images/extraction-card-1-cropped.png",
            aspect: 1452 / 1800,
            height: "107.360%",
            top: "8.23%",
            left: "25%",
            rotate: 3.38,
            rounded: "13px",
          },
          {
            src: "/images/extraction-card-2.png",
            aspect: 1056 / 594,
            height: "38.337%",
            top: "80.8315%",
            left: "3.626%",
            rotate: -4.89,
            rounded: "18px",
            shadow: "0px 2px 4px rgba(0,0,0,0.2)",
          },
          {
            src: "/images/extraction-card-3.png",
            aspect: 1056 / 594,
            height: "38.337%",
            top: "38%",
            left: "1.838%",
            rotate: 1.85,
            rounded: "12px",
            shadow: "0px 2px 4px rgba(0,0,0,0.2)",
          },
          {
            src: "/images/extraction-card-4.png",
            aspect: 1056 / 594,
            height: "38.337%",
            top: "7%",
            left: "2.712%",
            rotate: -8,
            rounded: "18px",
            shadow: "0px 2px 4px rgba(0,0,0,0.2)",
          },
        ],
        mobile: [
          {
            src: "/images/extraction-card-1-cropped.png",
            aspect: 1452 / 1800,
            height: "107.360%",
            top: "8.23%",
            left: "33%",
            rotate: 3.38,
            rounded: "13px",
          },
          {
            src: "/images/extraction-card-2.png",
            aspect: 1056 / 594,
            height: "38.337%",
            top: "80.8315%",
            left: "3.626%",
            rotate: -4.89,
            rounded: "12px",
            shadow: "0px 2px 4px rgba(0,0,0,0.2)",
          },
          {
            src: "/images/extraction-card-3.png",
            aspect: 1056 / 594,
            height: "38.337%",
            top: "40%",
            left: "1.838%",
            rotate: 1.85,
            rounded: "12px",
            shadow: "0px 2px 4px rgba(0,0,0,0.2)",
          },
          {
            src: "/images/extraction-card-4.png",
            aspect: 1056 / 594,
            height: "38.337%",
            top: "10%",
            left: "2.712%",
            rotate: -8,
            rounded: "12px",
            shadow: "0px 2px 4px rgba(0,0,0,0.2)",
          },
        ],
      },
    },
    cta: {
      label: "Read more",
      href: "https://www.figma.com/slides/8v5EUyaPZdJariwZpRokns",
      external: true,
    },
  },
  {
    slug: "platform-reskin", 
    company: "Pienso",
    logo: "/images/logo-pienso.svg",
    logoAlt: "Pienso",
    logoAspect: 139.034 / 32,
    headline: "A comprehensive platform reskin that’s more than skin-deep",
    body: "Pienso had grown into a sprawling platform without establishing a formal design system. We needed one, and to clean up a lot of UX debt along the way.",
    tags: ["UX", "design systems", "leadership"],
    hero: {
      alt: "Pienso platform reskin and design-system work in Figma",
      artwork: {
        desktop: [
          {
            src: "/images/reskin-slides.png",
            aspect: 3164 / 1950,
            height: "100%",
            top: "10%",
            left: "1%",
            rotate: 0,
            rounded: "6px",
          },
          {
            src: "/images/reskin-explore.png",
            aspect: 2880 / 1600,
            height: "81.360%",
            top: "35%",
            left: "19.668%",
            rotate: -5,
          },
        ],
        mobile: [
          {
            src: "/images/reskin-explore.png",
            aspect: 2880 / 1600,
            height: "105%",
            top: "8%",
            left: "8%",
            rotate: 5,
          },
        ],
      },
    },
    cta: {
      label: "Read more",
      href: "https://www.figma.com/slides/2gUHRCuqu0ttuDYnMumjtm",
      external: true,
    },
  },
  {
    slug: "wifc-kits",
    company: "WIFC",
    logo: "/images/logo-wifc.svg",
    logoAlt: "WIFC",
    logoAspect: 139.034 / 32.0029,
    headline: "Soccer uniforms that 140+ teammates can all agree on",
    body: "My amateur club had 5 teams, an established brand identity, and some worn-out kits. As a senior player and designer, I was excited to develop new home and away concepts.",
    tags: ["visual design", "side projects"],
    hero: {
      alt: "WIFC home and away soccer kit concepts",
      artwork: {
        desktop: [
          {
            src: "/images/wifc-screenshot.png",
            aspect: 3164 / 1932,
            height: "66.985%",
            top: "16.507%",
            left: "31.397%",
            rotate: 0,
            rounded: "2px",
          },
          {
            src: "/images/wifc-action-photo.jpg",
            aspect: 2048 / 1366,
            height: "43.331%",
            top: "54.093%",
            left: "16.343%",
            rotate: 0,
          },
          {
            src: "/images/wifc-team-photo.jpg",
            aspect: 4672 / 7008,
            height: "63.442%",
            top: "7.254%",
            left: "0%",
            rotate: 0,
          },
        ],
        mobile: [
          {
            src: "/images/wifc-action-photo.jpg",
            aspect: 2048 / 1366,
            height: "100%",
            top: "5%",
            left: "16.343%",
            rotate: 0,
          },
          {
            src: "/images/wifc-team-photo.jpg",
            aspect: 4672 / 7008,
            height: "100%",
            top: "5%",
            left: "0%",
            rotate: 0,
          },
        ],
      },
    },
    cta: {
      label: "Read more",
      href: "https://www.figma.com/slides/aXcuBTQNVp5nHMtlKUIjhe",
      external: true,
    },
  },
];
